### ISSUE TITLE
Add accessibility support to video controls.

### ISSUE THREAD

**Issue by nim23** [mderrick/react-html5video#1]

**Comment by mderrick** [comment]
Addressed in branch [1.2.0](https://github.com/mderrick/react-html5video/tree/1.2.0) in commits 20b03186d55128246efa97dccb7146335285a724 2044bc733489bc403af7a21d61ab9c9c80075798 a201268c8efc96d5a7c7af0bf9cbf3c3a38296dc yet to be released. My knowledge of a11y is limited. If you have any other input on this please let me know!
