### ISSUE TITLE
change Loading icon and error icon 

### ISSUE THREAD

**Issue by bsxz0604** [mderrick/react-html5video#103]
Sorry for that i know it's not a issue. 
but when i use , i want change loading icon, i try to  change css for this but it failed .
can you told me  how to change icon? Can  i do that? Thanks a lot

**Comment by mderrick** [comment]
Not really. The default player is more a working example than the product itself. You'd have to create a new player using the HoC which is obviously a larger task.

**Comment by bsxz0604** [comment]
Thanks a lot
