### ISSUE TITLE
Video AutoPlay is not working in Mobile Device

### ISSUE THREAD

**Issue by chandan7193** [mderrick/react-html5video#105]
`<Video autoPlay muted
                  className="book VideoPlayerMargin"
                    poster={Image1}
                    onCanPlayThrough={() => {
                        
                    }}>
                    <source src="ahsbsah.mp4" type="video/mp4"  />

          </Video>`

**Comment by mderrick** [comment]
Not really sure on the question but Mobile devices have certain restrictions around autoPlay. Please read https://webkit.org/blog/6784/new-video-policies-for-ios/ as this may answer your problem.
