### ISSUE TITLE
Subtitle/Caption track support

### ISSUE THREAD

**Issue by ypt** [mderrick/react-html5video#11]
Hi @mderrick, great project, nice job on a11y. 

Quick question - are there any plans to implement subtitle or caption tracks in the near future?

For example, maybe supporting something like this in the component API:

``` jsx
<Video controls autoPlay loop muted poster="http://sourceposter.jpg">
  <source src="http://sourcefile.webm" type="video/webm" />
  <track kind="captions" src="sampleCaptions.vtt" srclang="en" />
  <track kind="subtitles" src="sampleSubtitles_de.vtt" srclang="de" />
  <track kind="subtitles" src="sampleSubtitles_en.vtt" srclang="en" />
  <track kind="subtitles" src="sampleSubtitles_ja.vtt" srclang="ja" />
  <track kind="subtitles" src="sampleSubtitles_oz.vtt" srclang="oz" />
</Video>
```

And then displaying a subtitle/caption track selection menu among the other video player controls.

**Comment by mderrick** [comment]
Hi @ypt.

I would love to implement this for sure except time is tight lately. I won't be able to get round to it for a couple of months I would imagine. 

However that is how I would imagine the API to be, it's on my list of todos but if you cannot wait, pull requests are always welcome! :smile: I would need to work on a better dev setup though, its a bit clumsy right now.

**Comment by mderrick** [comment]
This is now supported in [v2.0.0](https://github.com/mderrick/react-html5video/releases/tag/v2.0.0)
