### ISSUE TITLE
[Recommendation] Expose default controls

### ISSUE THREAD

**Issue by thomassuckow** [mderrick/react-html5video#114]
I see a lot of hesitation in v2 to reimplement the default player, even when that may be the best way forward. I think part of it is that the default controls work well and currently you have to copy the default player wholesale if you want to customize it. If the default controls were exported in the library along with the DefaultPlayer.css, then a user could make their own player by simply copying the DefaultPlayer.js and they could reimplement a control only when needed.

Just a thought. I don't particularly need this capability if my PR is accepted, but I can see others benefiting.

**Comment by godcore** [comment]
Hi, I've implemented this in #115. In my project, I need almost DefaultPlayer but with some little changes in controls, so this works good for me

**Comment by mderrick** [comment]
Released in 2.5! Thanks for your help :)
