### ISSUE TITLE
How to remove console warning Received NaN for numeric attribute `value`. If this is expected, cast the value to a string.     in input

### ISSUE THREAD

**Issue by anilljoshi** [mderrick/react-html5video#123]
Received NaN for numeric attribute `value`. If this is expected, cast the value to a string. in input. this warning is also available on your demo. Please suggest how can we get ride from this console warning

**Comment by mderrick** [comment]
I fixed and released this for you in [v2.5.1](https://github.com/mderrick/react-html5video/tree/v2.5.1). It will be published to NPM within the hour. Thanks!

**Comment by anilljoshi** [comment]
its working now thanks
