### ISSUE TITLE
Any plans to expose status events on component?

### ISSUE THREAD

**Issue by rasmusfl0e** [mderrick/react-html5video#16]
Things like onCanPlayThrough, onDurationChange, onLoadedMetadata etc would be nice to have exposed on the component level. Do you have any plans to add something like that?

I could give it a go if nothing else :)

**Comment by mderrick** [comment]
Hi @rasmusfl0e thank you for raising an issue.

I went ahead and done this and released [1.2.6](https://github.com/mderrick/react-html5video/tree/1.2.6). Let me know if it does the trick!

**Comment by rasmusfl0e** [comment]
Wow - thanks, that was quick!

Works like a charm :)
