### ISSUE TITLE
video status

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [mderrick/react-html5video#21]
How to find out a video status.
I mean it is playing now or paused?

And can we access functions like pause, play with class or id selectors.

"this.refs.video.pause()" is working fine but coming to "this.refs.video.paused" giving result as undefined.

**Comment by Frezc** [comment]
use `this.refs.video.state.paused`.

**Comment by mderrick** [comment]
You need to access the DOM element if you want to use the [video API](https://www.w3.org/2010/05/video/mediaevents.html) directly. The React component UI will update accordingly if you modify it's state this way.

e.g `document.getElementsByTagName('video')[0].paused`.

You can see how I have used this in the [demo](https://mderrick.github.io/react-html5video/). Specifically [this line](https://github.com/mderrick/react-html5video/blob/master/demo/src/components/index/main/Main.js#L77).

**Comment by HarshaVardhanPVK** [comment]
Thanq very much, "document.getElementsByTagName('video')[0].paused" really helped me and "this.refs.video.state.paused" also worked.
