### ISSUE TITLE
Dealing with multiple players in single page

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [mderrick/react-html5video#22]
In a single webpage I am displaying number of "react-html5video" players. 
I want to pause current playing video while playing another video.

Can any one suggest me a correct process to overcome this.

Thanq...

**Comment by Frezc** [comment]
You can add the CustomComponent as Video 's child, and expose a prop like 
`isPlaying: React.PropTypes.bool.isRequired`
In your CustomComponent, implement `componentWillReceiveProps` method. Inside it call `this.props.play() or this.props.pause()`.
If you wanna auto pause while playing another, try to manage with root app's state.

**Comment by mderrick** [comment]
I don't know how you are maintaining your apps state so architecturally I'm not sure I have a specific answer for you.

However you can pass `onPlay={() => { // Pause all other videos. }}` prop to each video and in there, loop over the remaining videos (except the current one) and pause them all.

**Comment by HarshaVardhanPVK** [comment]
Thanq for your response, I achieved this by "document.getElementsByTagName('video')[i].pause()".

I just paused remaining all videos except current clicked one by using a loop.
