### ISSUE TITLE
Customising player

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [mderrick/react-html5video#23]
I want to customise the player and want to add a draggable div on the seek-bar of the player.

As shown in this link.
http://bit.ly/1px5qUh

By modifying some content in "ReactHtml5Video.js" file I achieved something like
http://bit.ly/1R6mvdz

But the selected seek-bar area should be draggable, I mean by dragging it we can select required part of the video.

Can you please provide any support in customising your player.
Thank you.

**Comment by mderrick** [comment]
The SeekBar is just a range input but with `opacity: 0` as pictured below with the opacity re-applied. The range input handle is naturally draggable.

![screen shot 2016-03-09 at 14 21 55](https://cloud.githubusercontent.com/assets/1044686/13638052/6e890484-e602-11e5-8d96-1c8d84805055.png)

If you want to customize a component I'd suggest creating a new one based upon [the original](https://github.com/mderrick/react-html5video/blob/master/src/components/progressbar/ProgressBar.js) but with your own styles. I'd would also use the same opacity trick but you can also style a range input directly [like this](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/).
