### ISSUE TITLE
Warning message.

### ISSUE THREAD

**Issue by mrbinky3000** [mderrick/react-html5video#28]
```
      <Video
        classNames={cssClasses}
        poster={this.props.poster}
        controls autoPlay loop muted
      >
        {this.props.sources.map((source, idx) =>
          <source key={idx} {...source} />
        )}
      </Video>
```

```warning.js:44 Warning: Controls: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)```

**Comment by mderrick** [comment]
Thanks for the bug. It should be fixed now in version [1.2.8](https://github.com/mderrick/react-html5video/tree/1.2.8)
