### ISSUE TITLE
crashes when video component is created / destroyed

### ISSUE THREAD

**Issue by WestleyArgentum** [mderrick/react-html5video#35]
I have some of these video components in lists, and when you scroll the video components are created / destroyed as needed (so that only currently viewable videos are being rendered).

But I've noticed that when the components are destroyed I start seeing tons of errors like
`ReactHtml5Video.js:329 Uncaught TypeError: Cannot read property 'duration' of null`

I've also seen infinite recursive loops and other things that cause the page to hang.

Is there a way to avoid this? To create and destroy these video components dynamically?

**Comment by mderrick** [comment]
Lazy loading video elements sounds like this may be pretty intensive for the browser anyway, this alone could be causing crashes maybe. Despite this the video player should destroy itself gracefully and it certainly sounds like an issue I need to solve. I've got a list stacking up, will try take a look ASAP.

**Comment by mderrick** [comment]
I've had an investigation in to this but I cannot seem to replicate the problem when I remove and re-add the Video component. Would you be able to put up an example or elaborate on how exactly you are destroying your videos?

**Comment by hew** [comment]
I can replicate this. 

I get the duration error (👆) any time I use ``react-router``'s ``<Link>`` to change the location.

**Comment by markplindsay** [comment]
I am seeing this too, in a similar "dynamically remove <video> elements that are far outside of the viewport" maneuver like @WestleyArgentum's, and also with navigation like @hew observed. Luckily my browser is not crashing, but I get plenty of `Cannot read property 'duration' of null` errors.

Would adding a check in `updateStateFromVideo` (https://github.com/mderrick/react-html5video/blob/08658353826d70536dd68e8d6a86ed8946ba3516/src/components/video/Video.js#L237-L254) — or wherever else `videoEl` is accessed directly — be a satisfactory solution?

Btw I love react-html5video and I am happy to make a PR for this, but I wanted to check first to see if a simple check is the wrong approach entirely.

**Comment by bushmango** [comment]
I'm also seeing it but love the component!

**Comment by mderrick** [comment]
Released fix in [1.2.12](https://github.com/mderrick/react-html5video/releases/tag/1.2.12). Please let me know if this solves it!

**Comment by markplindsay** [comment]
The fix is working 100% here. Thank you very much.

**Comment by mderrick** [comment]
Thanks @markplindsay. Will close!

**Comment by WestleyArgentum** [comment]
Thanks a ton, all
