### ISSUE TITLE
warning unknown prop 'copyKeys'

### ISSUE THREAD

**Issue by luismartinez85** [mderrick/react-html5video#36]
when i load video show in console
warning.js:44 Warning: Unknown prop `copyKeys` on <video> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

use a simple code
       <Video autoPlay loop  muted>
            <source src="URL_VIDEO" type="video/mp4" /> 
        </Video>

**Comment by aditcoding** [comment]
I have the same problem. Did you find a solution?

**Comment by mderrick** [comment]
Released in https://github.com/mderrick/react-html5video/releases/tag/1.2.10
