### ISSUE TITLE
Make Focus Class customizable

### ISSUE THREAD

**Issue by BraunreutherA** [mderrick/react-html5video#39]
Hi, is there a way to customize the `video--focused` class? It'd be very nice to give it the css class which it should apply when it's focused.

**Comment by mderrick** [comment]
Hi @BraunreutherA, thanks for the issue and PR.

Would you be able to elaborate on why you would want to use a unique className? For example why wouldn't you just style using the `video--focused` that already exists? As soon as you provide your own one you will lose the default functionality that is provided (which is perfectly acceptable to override if you want to).

**Comment by BraunreutherA** [comment]
I'm not working with one big css - I'm working with css modules where it's a nice approach to give css classes to the components

**Comment by mderrick** [comment]
You can always use [global](https://github.com/css-modules/css-modules#exceptions) CSS `:global(.video--focused) { height: 100%; }` in your CSS module file which would solve this for you. 

Obviously this is a little bit lame but as we pass the className straight through you can also do something like this to keep the CSS less global:

```
import styles from 'component.css';
<Video className={styles.customVideoClass} />
```
`.customVideoClass:global(.video--focused) {}`

Where else would you think you need to have classes like this? Only the video and the wrapper? I wouldn't want to start adding these classes to the other Controls and Overlay components for example when they can be modified globally or we will end up with a really messy prop API.

**Comment by BraunreutherA** [comment]
At the moment only atthe video and the wrapper. But the global css module stuff seams to be good enough. didn't no this works - Thank you a lot! :)

**Comment by mderrick** [comment]
No worries, let me know how it goes! [CSS modules FTW](https://twitter.com/mattjderrick/status/666716910197809152).

**Comment by BraunreutherA** [comment]
The `.customVideoClass:global(.video--focused) {}` does work but how would you apply it to the inner video tag? I tried `.customVideoClass:global(.video__el) {}`but there's no effect.

**Comment by mderrick** [comment]
Your selector is wrong.

`.customVideoClass:global(.video__el) {}` is equal to `.customVideoClass.video__el {}`. It should be `.customVideoClass :global(.video__el) {}` (note the space).
