### ISSUE TITLE
Performances on playback/volume progress bar

### ISSUE THREAD

**Issue by Grsmto** [mderrick/react-html5video#43]
- Volume seems janky/laggy cause of the throttling function applied on the media events (100ms). Removing it makes the volume bar super smooth.
- Playback is slow cause I guess it performs lot of actions on user interaction (I didn't dig into this).

I'm currently working on a PR to fix this (I have a result with both bar being smooth, keeping the progress bar input value controlled) but wanting to have your opinion on this or any hint/idea you would have had.

Thanks.

**Comment by mderrick** [comment]
I wanted to throttle as much as possible because I was worried about the amount of renders being caused by the video as it's a lot. If we can find a trade off between number of renders and smoothness that would be great (or if you can convince me that we don't care that it renders that often then I'm OK). Thanks.

**Comment by Grsmto** [comment]
Did you have performances issues in the first place?
Cause it's quite ironic that a performance optimisation is causing a performances issue :p
Anyway, I will post my solution as a PR and I'll let you see.

**Comment by mderrick** [comment]
I just wanted to keep the number of renders down. It's not so much a performance issue that I had originally just something I wasn't comfortable with. If removing it makes a huge difference in how smooth those seek bars are then I think removing it could be OK (or throttling to a much smaller number). I will have a play with the value later to also see if it makes much difference.
