### ISSUE TITLE
Override Scrub Method

### ISSUE THREAD

**Issue by drsmall** [mderrick/react-html5video#49]
I'd like to disable scrubbing when the user tries to watch part of the video they haven't reached.
So if I have a method that calculates that, how can I override he default seeking method with my own?

**Comment by mderrick** [comment]
You can override the default seekbar by simply creating your own component and providing it as a child as mentioned in [this section](https://github.com/mderrick/react-html5video#advanced-usage).

I'd recommend that you simply look at [the original seekbar](https://github.com/mderrick/react-html5video/blob/master/src/components/controls/seek/Seek.js), and the props it receives then utilise them to build your own custom seek bar logic.
