### ISSUE TITLE
Give Alert Message If Source File Format Is Invalid or Not Supported

### ISSUE THREAD

**Issue by agungsb** [mderrick/react-html5video#50]
I'm wondering if it's possible to give any alert when the source file format is not invalid or not supported instead of display plain text message.

Any thought?

**Comment by agungsb** [comment]
After further learning to the source code, I found out that I can manage to do it with onError. It should have been documented.

**Comment by mderrick** [comment]
Thanks for the issue. I believe the documentation you are looking for is [here](https://github.com/mderrick/react-html5video#simple-usage). You can supply all the [React media events](https://facebook.github.io/react/docs/events.html#media-events) which includes `onError`. Your use case is very specific, so I wouldn't want to document it.
