### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined(…)

### ISSUE THREAD

**Issue by zdila** [mderrick/react-html5video#56]
If there is no `<source>` in `<Video>` element and `src=` is specified directly, then it errors with `Uncaught TypeError: Cannot read property 'addEventListener' of undefined(…)` in `ReactHtml5Video.componentDidMount`.

**Comment by mderrick** [comment]
Fixed in [v2.0.0](https://github.com/mderrick/react-html5video/releases/tag/v2.0.0)
