### ISSUE TITLE
Is there any way to tell if the user finished viewing the video?

### ISSUE THREAD

**Issue by Aviglik91** [mderrick/react-html5video#57]
hey ,
Is there any way to tell if the user finished viewing the video?

**Comment by mderrick** [comment]
You can use any of event listeners that a [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) supports. In this case  `ended` https://developer.mozilla.org/en-US/docs/Web/Events/ended might be best.

```
<Video onEnded={(e) => console.log(e)}>
```
