### ISSUE TITLE
Wrong current time and video length showing on Mac - Chrome

### ISSUE THREAD

**Issue by BernardoFBBraga** [mderrick/react-html5video#58]
On the demo http://mderrick.github.io/react-html5video/
The current time shows as 23:00:00 at the start of the video
The end time or duration shows as 23:09:56
Bug does not reproduce on Safari, only on Google Chrome
Bug occurs in all 3 video samples. Bug shows even while video is not loaded (in which case the duration shows as 23:00:00)

System is OSX El Capitain version 10.11.6
Chrome Version 54.0.2840.98 (64-bit)

**Comment by BernardoFBBraga** [comment]
Bug occurs in all 3 video samples. Bug shows even while video is not loaded (in which case the duration shows as 23:00:00)

**Comment by BernardoFBBraga** [comment]
Chrome:
var date = new Date(null);
undefined
date
Wed Dec 31 1969 21:00:00 GMT-0300 (BRT)

Safari:
> var date = new Date(null);
< undefined
> date
< Wed Dec 31 1969 22:00:00 GMT-0200 (BRST)

Seems to be some timezone browser specificity

**Comment by BernardoFBBraga** [comment]
It seems changing the date declaration to new Date(Date.UTC(2000,01,01,0,0,0,0)) fixes the issue. I'll do a pull request

**Comment by mderrick** [comment]
Hi,
Thanks for the issue.

I'm not able to replicate this even with the same OS and Browser is there any more information you can provide?

Can you try `new Date(0)` as this should work also.

**Comment by BernardoFBBraga** [comment]
@mderrick I am in Brazil, I think it has to do with timezones and daylight savings time
my solution as stated above did not compile, I get the following error:
![screen shot 2016-11-28 at 1 32 29 pm](https://cloud.githubusercontent.com/assets/3694228/20674216/39e9571e-b56f-11e6-9506-a7c97f6c0a8f.png)
Your suggestion does not fix the issue

**Comment by mderrick** [comment]
Released in 1.3.0
