### ISSUE TITLE
iOS always showing loader

### ISSUE THREAD

**Issue by yodiman** [mderrick/react-html5video#63]
The issue is that iOS without user interaction only preloads video metadata (readyState = 1 HAVE_METADATA) and Spinner is showed on the video until user clicks on it. Only after that video begins loading reaching readyState = HAVE_ENOUGH_DATA and starts to play.

I think that has a sense to add iOS check and set in Video.js if it's iOS:
`loading: this.videoEl.readyState < this.videoEl.HAVE_METADATA`

**Comment by Enijar** [comment]
For anyone looking for a temporary fix for this on mobile, trigger the load event, like so.

```js
<Video ref="video"/>

$(this.refs.video).trigger('load');
```

**Comment by tomkis1** [comment]
What's the deal with this? It's quite a blocker for us. Would it be possible to merge #75? @yodiman's solution seems to be right.

**Comment by mderrick** [comment]
I've been busy release v2 so apologies for neglecting this. The problem with #75 is that this will happen on desktop devices too. I want to avoid any device detection where possible so need to evaluate the impact if I do change that for all devices. I will tackle this ASAP.

**Comment by 99wesley99** [comment]
Do we have an ETA on this fix?

**Comment by mderrick** [comment]
It's still on my todo list and I'm not sure the PR tackles the issue fully.
