### ISSUE TITLE
Get the reason of a source error

### ISSUE THREAD

**Issue by macnibblet** [mderrick/react-html5video#64]
I'm trying to get the reason of a source error by hooking into the onError media event, but I cannot find any information regarding the actual error. In my case it's our api responding with a `402` error telling that the client needs to pay to use our service.

**Comment by mderrick** [comment]
Hi @macnibblet I believe the error in the `onError` callback natively doesn't provide any information. I think you have to source this off the video properties. e.g [networkState](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/networkState) might reveal information and also [error codes](https://developer.mozilla.org/en-US/docs/Web/API/MediaError).
