### ISSUE TITLE
How to correctly use the 'paused' attribute?

### ISSUE THREAD

**Issue by idleherb** [mderrick/react-html5video#66]
I tried to get it working, but changing the attribute does not seem to have an effect: https://jsfiddle.net/7s9a311q/36/

**Comment by mderrick** [comment]
There is no such thing as a 'paused' attribute for a HTML5 Video element. The only supported attributes are [documented here](https://developer.mozilla.org/en/docs/Web/HTML/Element/video).

**Comment by idleherb** [comment]
You're right, I misinterpreted the docs. Using the .pause( ) event now.
