### ISSUE TITLE
How to pass player control components into a Custom Controls component?

### ISSUE THREAD

**Issue by vandervidi** [mderrick/react-html5video#68]
Like something like this?

<Video controls autoPlay loop muted poster="http://sourceposter.jpg">
            <source src="http://sourcefile.mp4" type="video/mp4" />
            <source src="http://sourcefile.webm" type="video/webm" />

            <Overlay />
            <Controls>
                **<CustomControlComponent >**
                       **<Play />**
                       **<Seek />**
                       **<Time />**
                       **<Mute />**
                       **<Fullscreen />**
                **</CustomControlComponent />**
            </Controls>
        </Video>

**Comment by mderrick** [comment]
Sorry for the delayed response, I've been on a long holiday.

I'm not entirely sure on your question. Can you elaborate please?

**Comment by mderrick** [comment]
Closed due to not understanding the issue
