### ISSUE TITLE
Is there any way to support .flv format

### ISSUE THREAD

**Issue by DinakaranS** [mderrick/react-html5video#69]
Hi,

This component is really great, is there any way to add .flv format videos files.

I am getting video can't be played in this browser error.

**Comment by mderrick** [comment]
This component is only intended to simply add custom controls to a [HTML5 video](https://developer.mozilla.org/en/docs/Web/HTML/Element/video). FLV videos are not supported in many/any browsers and I don't intend to do anything with flash I'm afraid. You might want to look at [video.js](http://videojs.com/) (which uses flash) or look at converting your video to a more browser friendly format.
