### ISSUE TITLE
setting for IE 11

### ISSUE THREAD

**Issue by kwangkim** [mderrick/react-html5video#7]
I am using react-html5video.
Using webpack+babel, I can compile and use it with chrome and safari without problem.
But for IE 11, I got object.assign error.
To avoid above error, I added https://github.com/es-shims/es6-shim/ which is not necessary for other browsers.
Could you give me an advice?
If you also provide es5 version, I will appreciate it.
I attached my webpack.config.js
```
/* global __dirname */

var path = require('path');
var webpack = require('webpack');

var CopyWebpackPlugin = require('copy-webpack-plugin');

var dir_js = path.resolve(__dirname, 'js');
var dir_html = path.resolve(__dirname, 'html');
var dir_build = path.resolve(__dirname, 'build');
var dir_dist = path.resolve(__dirname, 'dist');

module.exports = {
    entry: path.resolve(dir_js, '10.js'),
    output: {
        path: dir_dist,
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                loader: 'babel-loader',
                test: /\.js$/,
                query: {
                    presets: ['es2015', 'react',"stage-0"],
                },
            },
        ]
    },
    plugins: [
        new CopyWebpackPlugin([
            { from: dir_html } // to: output.path
        ]),
        new webpack.NoErrorsPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress:{
                warnings: true
            }
        }),
    ],
    stats: {
        // Nice colored output
        colors: true
    },
};
```

**Comment by mderrick** [comment]
Ah, I will have to update the UMD build to use http://babeljs.io/docs/plugins/transform-object-assign/.

In the mean time you could use that in your Webpack config instead of using the polyfill. I'm pretty sure that `Object.assign` is the only think that needs transforming.

Let me know if that works and I will try solve this over the weekend.

**Comment by kwangkim** [comment]
I just forked your repo and add 
```
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',

                 query: {
                        presets: ['es2015', 'react','stage-0'],
                        plugins: ['transform-object-assign']
                },
            },
```
It works great!
Thank you very much for your suggestion.
[Link](https://github.com/kwangkim/react-html5video/blob/master/webpack.config.js)

**Comment by mderrick** [comment]
Excellent. I will take a look at this ASAP. Thanks!

**Comment by mderrick** [comment]
Updated readme with information on using a polyfill or using of babel-runtime in order to ensure `Object.assign` and other ES6 features work. Deployed a new working UMD build with babel-runtime.

https://github.com/mderrick/react-html5video/commit/eaf26ab5f0f46caccd163193c9d28a428d06cd41
