### ISSUE TITLE
youtube or vimeo videos error

### ISSUE THREAD

**Issue by jasan-s** [mderrick/react-html5video#71]
I tried updating source in the jsfiddle example to a youtube video and vimeo video link, but I get the error that Video cannot be played in this browser

**Comment by mderrick** [comment]
Could you provide the exact link please?

**Comment by jasan-s** [comment]
@mderrick i.e  https://www.youtube.com/watch?v=F_GEISRSPrY

**Comment by mderrick** [comment]
Do you mean you literally want to do:

```
<source src="https://www.youtube.com/watch?v=F_GEISRSPrY" />
```

If so then this will never work. This player is just a HTML5 video wrapper and takes a [supported video source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source). There is no magic.
