### ISSUE TITLE
Fullscreen does not show custom control bar

### ISSUE THREAD

**Issue by dennyferra** [mderrick/react-html5video#72]
The custom control bar does not appear in fullscreen.

I believe this would be a fairly trivial fix. In order to get the control bar to appear in full screen you just need to call requestFullScreen on the container instead of the video element.

For example in https://github.com/mderrick/react-html5video/blob/master/src/components/video/Video.js#L155 you could use `videoEl.parentElement` to accomplish this.

I can submit a pull request for this.

**Comment by mderrick** [comment]
Thanks for the issue, this indeed is a nice feature. I'm currently working on a v2 branch and have [implemented it there](https://github.com/mderrick/react-html5video/commit/6276dc982a0ca54fd5812e0e98e7004bf43f46f5).

I wasn't planning on adding new features to v1 anymore. Do you require this in v1?

**Comment by dennyferra** [comment]
@mderrick Awesome! I have no need to update v1 I actually had to customize the fullscreen code to do some additional things so I have my own fullscreen implementation. Looking forward to v2, thanks!
