### ISSUE TITLE
Running npm install Error

### ISSUE THREAD

**Issue by jasan-s** [mderrick/react-html5video#73]
I downloaded the git repo ran npm install I get multiple errors related to git cloning. `Permission denied Make sure You have correct access rights `

**Comment by mderrick** [comment]
I believe this is probably an issue with your npm/git setup. What repository do you not have access to specifically? It's possible it could be `coding-standards` but this is publicly accessible, your setup just might not like `ssh`. I will be releasing [v2](https://github.com/mderrick/react-html5video/tree/v2) soon which has a much easier development process.

**Comment by jasan-s** [comment]
I look forward to that. :)

**Comment by mderrick** [comment]
Fixed in [v2.0.0](https://github.com/mderrick/react-html5video/releases/tag/v2.0.0) (I hope!).
