### ISSUE TITLE
Does not refresh if source URL changes

### ISSUE THREAD

**Issue by davidj-lynxlogic** [mderrick/react-html5video#8]
It looks like componentWillReceiveProps is not implemented. If the source URL changes, the video does not update.

**Comment by mderrick** [comment]
I'm not sure what you mean by "componentWillReceiveProps is not implemented" but if you change the src of a video, like any normal HTML5 video, you will then need to then call `.load()` on it.

You can see this in the demo: https://github.com/mderrick/react-html5video/blob/master/demo/src/components/index/main/Main.js#L23-L33

Does that answer your question?

**Comment by davidj-lynxlogic** [comment]
Ah, sorry my bad. I missed how that should work. I had expected that the component would detect a change in source URL and re-load automatically. But I see now how you designed it.
