### ISSUE TITLE
Volume, Fullscreen and svg icons alike incorrect size.

### ISSUE THREAD

**Issue by Bram-Zijp** [mderrick/react-html5video#82]
The demo's work fine but in my own build they need the following code to get the correct size. Chrome 56.0.2924.87 (64-bit)
```
        svg {
            width: 100%;
            height: 100%;
        }
```

**Comment by mderrick** [comment]
I cannot seem to replicate this issued. I am using the exact same browser version on Mac.

**Comment by mderrick** [comment]
Are you applying some global styles to to SVG's that is causing this?

**Comment by Bram-Zijp** [comment]
The reason is that I have box-sizing: border-box; as global style on everything. I'm sorry for the inconvenience.
