### ISSUE TITLE
In mobile browser player always show the loader not showing any thing until we touch the loader.

### ISSUE THREAD

**Issue by harikrypto** [mderrick/react-html5video#87]
I am trying react-html5video in my react app. In mobile browser player always show the loader not showing any thing until we touch the loader. here is my demo page have a [look](http://54.255.203.208/broadcast/1)

This also same for the demo page for this player when i checked in mobile.([Demo](http://mderrick.github.io/react-html5video/)).

 `<Video autoPlay loop muted
                       controls={['PlayPause', 'Seek', 'Time', 'Volume', 'Fullscreen']}
                       // poster={screenShotUrl}
                       onCanPlayThrough={() => {
                           overlay
                       }}>
                    <source src={videoUrl} type="video/mp4"/>
                </Video>`

Could you please check and can you provide a fix for this?

**Comment by mderrick** [comment]
This is a known issue, PR's welcome. Please see https://github.com/mderrick/react-html5video/issues/63
