### ISSUE TITLE
Recompose toClass method throwing Deprecated warning.

### ISSUE THREAD

**Issue by 13colours** [mderrick/react-html5video#91]
Requires updating Recompose package.

**Comment by mderrick** [comment]
I don't get this deprecation warning? What version of `recompose` is installed? The docs don't mention deprecating this: https://github.com/acdlite/recompose/blob/master/docs/API.md#toclass

**Comment by mderrick** [comment]
I cannot replicate this and I have now removed recompose anyway. Closing. Thanks!
