### ISSUE TITLE
Video does not refresh when new src is pushed by state

### ISSUE THREAD

**Issue by hamedmam** [mderrick/react-html5video#95]
I use this.state.video_src to be able to run a playlist.
When state changes by selecting new video from list the video src is inserted but does not stop the video and refresh the player

**Comment by hamedmam** [comment]
I just figured out that I need to call .load() but I still can not use ref in order to select video tag. I tried and it returned error . The example you had given in other closed issue was a broken link.

**Comment by mderrick** [comment]
What error did it return? You should be able to do something like this `https://github.com/mderrick/react-html5video/blob/master/demo/src/components/App.js#L31`
